// Code generated by protoc-gen-go. DO NOT EDIT.
// source: transaction.proto

package entity

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TransactionType int32

const (
	TransactionType_TRANF TransactionType = 0
	TransactionType_ISSUE TransactionType = 1
)

var TransactionType_name = map[int32]string{
	0: "TRANF",
	1: "ISSUE",
}
var TransactionType_value = map[string]int32{
	"TRANF": 0,
	"ISSUE": 1,
}

func (x TransactionType) String() string {
	return proto.EnumName(TransactionType_name, int32(x))
}
func (TransactionType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_transaction_622bc41cf5fa06c4, []int{0}
}

type Transaction struct {
	Type                 TransactionType `protobuf:"varint,1,opt,name=type,proto3,enum=entity.TransactionType" json:"type,omitempty"`
	Hash                 []byte          `protobuf:"bytes,2,opt,name=Hash,proto3" json:"Hash,omitempty"`
	Sign                 []byte          `protobuf:"bytes,3,opt,name=Sign,proto3" json:"Sign,omitempty"`
	Sender               []byte          `protobuf:"bytes,4,opt,name=Sender,proto3" json:"Sender,omitempty"`
	Timestamp            int64           `protobuf:"varint,5,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	Data                 []byte          `protobuf:"bytes,6,opt,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Transaction) Reset()         { *m = Transaction{} }
func (m *Transaction) String() string { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()    {}
func (*Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_transaction_622bc41cf5fa06c4, []int{0}
}
func (m *Transaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction.Unmarshal(m, b)
}
func (m *Transaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction.Marshal(b, m, deterministic)
}
func (dst *Transaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction.Merge(dst, src)
}
func (m *Transaction) XXX_Size() int {
	return xxx_messageInfo_Transaction.Size(m)
}
func (m *Transaction) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction proto.InternalMessageInfo

func (m *Transaction) GetType() TransactionType {
	if m != nil {
		return m.Type
	}
	return TransactionType_TRANF
}

func (m *Transaction) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *Transaction) GetSign() []byte {
	if m != nil {
		return m.Sign
	}
	return nil
}

func (m *Transaction) GetSender() []byte {
	if m != nil {
		return m.Sender
	}
	return nil
}

func (m *Transaction) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Transaction) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type BlockHeader struct {
	Version              int32    `protobuf:"varint,1,opt,name=Version,proto3" json:"Version,omitempty"`
	MagicCode            int32    `protobuf:"varint,2,opt,name=MagicCode,proto3" json:"MagicCode,omitempty"`
	Hash                 []byte   `protobuf:"bytes,3,opt,name=Hash,proto3" json:"Hash,omitempty"`
	Height               uint32   `protobuf:"varint,4,opt,name=Height,proto3" json:"Height,omitempty"`
	Timestamp            int64    `protobuf:"varint,5,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	PreHash              []byte   `protobuf:"bytes,6,opt,name=PreHash,proto3" json:"PreHash,omitempty"`
	Miner                []byte   `protobuf:"bytes,7,opt,name=Miner,proto3" json:"Miner,omitempty"`
	Count                int32    `protobuf:"varint,8,opt,name=Count,proto3" json:"Count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockHeader) Reset()         { *m = BlockHeader{} }
func (m *BlockHeader) String() string { return proto.CompactTextString(m) }
func (*BlockHeader) ProtoMessage()    {}
func (*BlockHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_transaction_622bc41cf5fa06c4, []int{1}
}
func (m *BlockHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockHeader.Unmarshal(m, b)
}
func (m *BlockHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockHeader.Marshal(b, m, deterministic)
}
func (dst *BlockHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockHeader.Merge(dst, src)
}
func (m *BlockHeader) XXX_Size() int {
	return xxx_messageInfo_BlockHeader.Size(m)
}
func (m *BlockHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockHeader.DiscardUnknown(m)
}

var xxx_messageInfo_BlockHeader proto.InternalMessageInfo

func (m *BlockHeader) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *BlockHeader) GetMagicCode() int32 {
	if m != nil {
		return m.MagicCode
	}
	return 0
}

func (m *BlockHeader) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *BlockHeader) GetHeight() uint32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *BlockHeader) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *BlockHeader) GetPreHash() []byte {
	if m != nil {
		return m.PreHash
	}
	return nil
}

func (m *BlockHeader) GetMiner() []byte {
	if m != nil {
		return m.Miner
	}
	return nil
}

func (m *BlockHeader) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

type Block struct {
	Header               *BlockHeader   `protobuf:"bytes,1,opt,name=Header,proto3" json:"Header,omitempty"`
	Trans                []*Transaction `protobuf:"bytes,2,rep,name=Trans,proto3" json:"Trans,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Block) Reset()         { *m = Block{} }
func (m *Block) String() string { return proto.CompactTextString(m) }
func (*Block) ProtoMessage()    {}
func (*Block) Descriptor() ([]byte, []int) {
	return fileDescriptor_transaction_622bc41cf5fa06c4, []int{2}
}
func (m *Block) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Block.Unmarshal(m, b)
}
func (m *Block) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Block.Marshal(b, m, deterministic)
}
func (dst *Block) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Block.Merge(dst, src)
}
func (m *Block) XXX_Size() int {
	return xxx_messageInfo_Block.Size(m)
}
func (m *Block) XXX_DiscardUnknown() {
	xxx_messageInfo_Block.DiscardUnknown(m)
}

var xxx_messageInfo_Block proto.InternalMessageInfo

func (m *Block) GetHeader() *BlockHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Block) GetTrans() []*Transaction {
	if m != nil {
		return m.Trans
	}
	return nil
}

func init() {
	proto.RegisterType((*Transaction)(nil), "entity.Transaction")
	proto.RegisterType((*BlockHeader)(nil), "entity.BlockHeader")
	proto.RegisterType((*Block)(nil), "entity.Block")
	proto.RegisterEnum("entity.TransactionType", TransactionType_name, TransactionType_value)
}

func init() { proto.RegisterFile("transaction.proto", fileDescriptor_transaction_622bc41cf5fa06c4) }

var fileDescriptor_transaction_622bc41cf5fa06c4 = []byte{
	// 333 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0xcd, 0x4e, 0x02, 0x31,
	0x14, 0x85, 0x2d, 0x43, 0x07, 0xb9, 0xf8, 0x83, 0xd5, 0x60, 0x17, 0x2e, 0x26, 0x6c, 0x44, 0x49,
	0x58, 0xe0, 0x13, 0x28, 0x6a, 0x70, 0x81, 0x31, 0x9d, 0xd1, 0xad, 0xa9, 0xd0, 0x40, 0xa3, 0xb4,
	0x93, 0x99, 0xba, 0xe0, 0x9d, 0x7c, 0x1d, 0xdf, 0xc7, 0xf4, 0x16, 0x64, 0xe2, 0xc6, 0xdd, 0x3d,
	0xa7, 0x27, 0x27, 0xdf, 0xcd, 0x2d, 0x1c, 0xb9, 0x42, 0x9a, 0x52, 0x4e, 0x9d, 0xb6, 0x66, 0x90,
	0x17, 0xd6, 0x59, 0x16, 0x2b, 0xe3, 0xb4, 0x5b, 0x75, 0xbf, 0x08, 0xb4, 0xb2, 0xed, 0x2b, 0xeb,
	0x43, 0xdd, 0xad, 0x72, 0xc5, 0x49, 0x42, 0x7a, 0x07, 0xc3, 0xd3, 0x41, 0x88, 0x0d, 0x2a, 0x91,
	0x6c, 0x95, 0x2b, 0x81, 0x21, 0xc6, 0xa0, 0x3e, 0x96, 0xe5, 0x82, 0xd7, 0x12, 0xd2, 0xdb, 0x13,
	0x38, 0x7b, 0x2f, 0xd5, 0x73, 0xc3, 0xa3, 0xe0, 0xf9, 0x99, 0x75, 0x20, 0x4e, 0x95, 0x99, 0xa9,
	0x82, 0xd7, 0xd1, 0x5d, 0x2b, 0x76, 0x06, 0xcd, 0x4c, 0x2f, 0x55, 0xe9, 0xe4, 0x32, 0xe7, 0x34,
	0x21, 0xbd, 0x48, 0x6c, 0x0d, 0xdf, 0x74, 0x2b, 0x9d, 0xe4, 0x71, 0x68, 0xf2, 0x73, 0xf7, 0x9b,
	0x40, 0xeb, 0xe6, 0xc3, 0x4e, 0xdf, 0xc7, 0x4a, 0xfa, 0x06, 0x0e, 0x8d, 0x17, 0x55, 0x94, 0xda,
	0x1a, 0x24, 0xa6, 0x62, 0x23, 0x7d, 0xf7, 0x44, 0xce, 0xf5, 0x74, 0x64, 0x67, 0x0a, 0x01, 0xa9,
	0xd8, 0x1a, 0xbf, 0xe4, 0x51, 0x85, 0xbc, 0x03, 0xf1, 0x58, 0xe9, 0xf9, 0xc2, 0x21, 0xe5, 0xbe,
	0x58, 0xab, 0x7f, 0x28, 0x39, 0x34, 0x9e, 0x0a, 0x85, 0x65, 0x01, 0x74, 0x23, 0xd9, 0x09, 0xd0,
	0x89, 0x36, 0xaa, 0xe0, 0x0d, 0xf4, 0x83, 0xf0, 0xee, 0xc8, 0x7e, 0x1a, 0xc7, 0x77, 0x91, 0x29,
	0x88, 0xee, 0x2b, 0x50, 0x5c, 0x8b, 0xf5, 0x3d, 0x84, 0x5f, 0x0d, 0xf7, 0x69, 0x0d, 0x8f, 0x37,
	0x17, 0xa8, 0x6c, 0x2d, 0xd6, 0x11, 0x76, 0x01, 0x14, 0x0f, 0xc3, 0x6b, 0x49, 0x54, 0xcd, 0x56,
	0xae, 0x25, 0x42, 0xe2, 0xf2, 0x1c, 0x0e, 0xff, 0xdc, 0x90, 0x35, 0x81, 0x66, 0xe2, 0xfa, 0xf1,
	0xbe, 0xbd, 0xe3, 0xc7, 0x87, 0x34, 0x7d, 0xbe, 0x6b, 0x93, 0xb7, 0x18, 0xff, 0xc7, 0xd5, 0x4f,
	0x00, 0x00, 0x00, 0xff, 0xff, 0xc3, 0x70, 0xcf, 0x6a, 0x34, 0x02, 0x00, 0x00,
}
